version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_plugins.yaml
    flatten: true
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/...'
      COMPONENTS: 'keystoreop/aws'
      GENERATE_DOCS_INDEX: "false"
