version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_library.yaml
    flatten: true
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/pkg/common/... {{.ROOT_DIR}}/pkg/keystoreop/... {{.ROOT_DIR}}/cmd/...'
      GENERATE_DOCS_INDEX: "false"
