// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.7
// source: proto/aws/v1/aws.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AWSKeyAccessData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyArn         string `protobuf:"bytes,10,opt,name=key_arn,json=keyArn,proto3" json:"key_arn,omitempty"`
	TrustAnchorArn string `protobuf:"bytes,20,opt,name=trust_anchor_arn,json=trustAnchorArn,proto3" json:"trust_anchor_arn,omitempty"`
	ProfileArn     string `protobuf:"bytes,30,opt,name=profile_arn,json=profileArn,proto3" json:"profile_arn,omitempty"`
	RoleArn        string `protobuf:"bytes,40,opt,name=role_arn,json=roleArn,proto3" json:"role_arn,omitempty"`
}

func (x *AWSKeyAccessData) Reset() {
	*x = AWSKeyAccessData{}
	mi := &file_proto_aws_v1_aws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AWSKeyAccessData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSKeyAccessData) ProtoMessage() {}

func (x *AWSKeyAccessData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aws_v1_aws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSKeyAccessData.ProtoReflect.Descriptor instead.
func (*AWSKeyAccessData) Descriptor() ([]byte, []int) {
	return file_proto_aws_v1_aws_proto_rawDescGZIP(), []int{0}
}

func (x *AWSKeyAccessData) GetKeyArn() string {
	if x != nil {
		return x.KeyArn
	}
	return ""
}

func (x *AWSKeyAccessData) GetTrustAnchorArn() string {
	if x != nil {
		return x.TrustAnchorArn
	}
	return ""
}

func (x *AWSKeyAccessData) GetProfileArn() string {
	if x != nil {
		return x.ProfileArn
	}
	return ""
}

func (x *AWSKeyAccessData) GetRoleArn() string {
	if x != nil {
		return x.RoleArn
	}
	return ""
}

var File_proto_aws_v1_aws_proto protoreflect.FileDescriptor

var file_proto_aws_v1_aws_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x77, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x61,
	0x77, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x6b, 0x65, 0x79, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x61, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x91, 0x01, 0x0a, 0x10, 0x41, 0x57, 0x53, 0x4b,
	0x65, 0x79, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07,
	0x6b, 0x65, 0x79, 0x5f, 0x61, 0x72, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b,
	0x65, 0x79, 0x41, 0x72, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x61,
	0x6e, 0x63, 0x68, 0x6f, 0x72, 0x5f, 0x61, 0x72, 0x6e, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x41, 0x72, 0x6e, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x61, 0x72, 0x6e, 0x18, 0x1e,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x6e,
	0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x61, 0x72, 0x6e, 0x18, 0x28, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x41, 0x72, 0x6e, 0x42, 0x2f, 0x5a, 0x2d, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x6b, 0x63,
	0x6d, 0x2f, 0x6b, 0x65, 0x79, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2d, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_aws_v1_aws_proto_rawDescOnce sync.Once
	file_proto_aws_v1_aws_proto_rawDescData = file_proto_aws_v1_aws_proto_rawDesc
)

func file_proto_aws_v1_aws_proto_rawDescGZIP() []byte {
	file_proto_aws_v1_aws_proto_rawDescOnce.Do(func() {
		file_proto_aws_v1_aws_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_aws_v1_aws_proto_rawDescData)
	})
	return file_proto_aws_v1_aws_proto_rawDescData
}

var file_proto_aws_v1_aws_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_aws_v1_aws_proto_goTypes = []any{
	(*AWSKeyAccessData)(nil), // 0: keystore_plugins.proto.aws.v1.AWSKeyAccessData
}
var file_proto_aws_v1_aws_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_aws_v1_aws_proto_init() }
func file_proto_aws_v1_aws_proto_init() {
	if File_proto_aws_v1_aws_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_aws_v1_aws_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_aws_v1_aws_proto_goTypes,
		DependencyIndexes: file_proto_aws_v1_aws_proto_depIdxs,
		MessageInfos:      file_proto_aws_v1_aws_proto_msgTypes,
	}.Build()
	File_proto_aws_v1_aws_proto = out.File
	file_proto_aws_v1_aws_proto_rawDesc = nil
	file_proto_aws_v1_aws_proto_goTypes = nil
	file_proto_aws_v1_aws_proto_depIdxs = nil
}
