name: Release New Version

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/release.svc.yaml@main
    secrets: inherit
