name: Compliance

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'LICENSES/**'
      - '.releases/**'
      - '.github/**'
  pull_request:

permissions:
  contents: read

jobs:
  check:
    uses: openkcm/build/.github/workflows/reuse.lib.yaml@main
    secrets: inherit
